//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Course
    {
        public Course()
        {
            this.Exams = new HashSet<Exam>();
            this.Questions = new HashSet<Question>();
            this.Students = new HashSet<Student>();
        }
        [Key]
        public int C_ID { get; set; }
        public string description { get; set; }
        public string Name { get; set; }
        public short Hour { get; set; }
        public int max_degree { get; set; }
        public int min_degree { get; set; }
        public int Instruct_ID { get; set; }
        public int Track_ID { get; set; }
        public Nullable<bool> is_deleted { get; set; }

         [ForeignKey("Instruct_ID")]
        public virtual Instructor Instructor { get; set; }
        [ForeignKey("Track_ID ")]
        public virtual Track Track { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
