//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class exam_question
    {
        public exam_question()
        {
            this.exam_question_Student = new HashSet<exam_question_Student>();
        }
         
     
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID_exam_question { get; set; }
        public int ex_id { get; set; }
        public int ID_question { get; set; }
       [ForeignKey("ex_id")]
        public virtual Exam Exam { get; set; }
        public virtual ICollection<exam_question_Student> exam_question_Student { get; set; }
        [ForeignKey("ID_question")]
        public virtual Question Question { get; set; }
    }
}
