//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Exam
    {
       

        public Exam()
        {
            this.exam_question = new HashSet<exam_question>();
            this.exam_Student = new HashSet<exam_Student>();
        }
    
        [Key]
        public int ex_id { get; set; }
        public int period { get; set; }

    
        public DateTime start_time { get; set; }
       
        public DateTime end_time { get; set; }
        public string exam_type { get; set; }
        public int instruct_id { get; set; }
        public int MCQ_Mark { get; set; }
        public int MCQ_NUM { get; set; }
        public int TF_Mark { get; set; }
        public int TF_NUM { get; set; }
        public int Article_Mark { get; set; }
        public int Article_NUM { get; set; }
        public int C_ID { get; set; }
    
        [ForeignKey("C_ID")]
        public virtual Course Course { get; set; }
        [ForeignKey("instruct_id")]
        public virtual Instructor Instructor { get; set; }
        public virtual ICollection<exam_question> exam_question { get; set; }
        public virtual ICollection<exam_Student> exam_Student { get; set; }
    }
}
