//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class exam_question_Student
    {
        public exam_question_Student()
        {
            this.answer_Article = new HashSet<answer_Article>();
            this.answer_mcq = new HashSet<answer_mcq>();
            this.answer_true_false = new HashSet<answer_true_false>();
        }
    [Key]
        public int ID_exam_question_Student { get; set; }
        public int ID_exam_question { get; set; }
        public int St_ID { get; set; }
    
        public virtual ICollection<answer_Article> answer_Article { get; set; }
        public virtual ICollection<answer_mcq> answer_mcq { get; set; }
        public virtual ICollection<answer_true_false> answer_true_false { get; set; }
        public virtual exam_question exam_question { get; set; }
        [ForeignKey("St_ID")]
        public virtual Student Student { get; set; }
       
    
    }
}
