//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Instructor
    {
        public Instructor()
        {
            this.Courses = new HashSet<Course>();
            this.Exams = new HashSet<Exam>();
        }
         [Key]
        public int Instruct_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MG_id { get; set; }
        public int brn { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> log_ID { get; set; }
    
        [ForeignKey("brn")]
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        [ForeignKey("log_ID")]
        public virtual Login Login { get; set; }
    }
}
