//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class intake_branch_track
    {
        public intake_branch_track()
        {
            this.Students = new HashSet<Student>();
        }
       [Key]
        public int id_intake_branch_track { get; set; }
        public int brn_id { get; set; }
        public int trk_id { get; set; }
        public int itk_id { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        [ForeignKey("brn_id")]
        public virtual Branch Branch { get; set; }
        [ForeignKey("itk_id")]
        public virtual Intake Intake { get; set; }
        [ForeignKey("trk_id")]
        public virtual Track Track { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
