//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MCQ_Choice
    {
        public MCQ_Choice()
        {
            this.answer_mcq = new HashSet<answer_mcq>();
        }
    
        [Key]
       
        public int MCQ_ID { get; set; }
        public string choice { get; set; }
        public Nullable<bool> istrue { get; set; }
        public int ID_question { get; set; }
    
        public virtual ICollection<answer_mcq> answer_mcq { get; set; }
        public virtual Question Question { get; set; }
    }
}
