//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Versionn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Student
    {
        public Student()
        {
            this.answer_Article = new HashSet<answer_Article>();
            this.answer_mcq = new HashSet<answer_mcq>();
            this.answer_true_false = new HashSet<answer_true_false>();
            this.exam_question_Student = new HashSet<exam_question_Student>();
            this.exam_Student = new HashSet<exam_Student>();
            this.Courses = new HashSet<Course>();
        }
    
        [Key]
        public int St_ID { get; set; }
        public string name { get; set; }
        public int id_intake_branch_track { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> log_ID { get; set; }
    
        public virtual ICollection<answer_Article> answer_Article { get; set; }
        public virtual ICollection<answer_mcq> answer_mcq { get; set; }
        public virtual ICollection<answer_true_false> answer_true_false { get; set; }
        public virtual ICollection<exam_question_Student> exam_question_Student { get; set; }
        public virtual ICollection<exam_Student> exam_Student { get; set; }
        [ForeignKey("id_intake_branch_track")]
        public virtual intake_branch_track intake_branch_track { get; set; }
        [ForeignKey("log_ID")]
        public virtual Login Login { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
